- job:
    name: 'verify-dns-config'
    description: 'Run tests for fuel-infra/dns-config'
    concurrent: true
    node: 'dns-verify'
    builders:
      - shell: |
          #!/bin/bash
          set -ex
          ./bin/test.sh
    properties:
      - heavy-job:
          weight: 1
    parameters:
      - string:
          name: GERRIT_REFSPEC
          default: 'refs/heads/master'
    scm:
      - git:
          branches:
            - $GERRIT_BRANCH
          remotes:
            - gerrit:
                refspec: $GERRIT_REFSPEC
                url: 'ssh://infra-ci@review.fuel-infra.org:29418/fuel-infra/dns-config'
                credentials-id: '70105253-c857-4463-a927-f47307911e45'
          choosing-strategy: gerrit
    triggers:
      - gerrit:
          trigger-on:
            - patchset-created-event
          projects:
            - project-compare-type: PLAIN
              project-pattern: 'fuel-infra/dns-config'
              branches:
                - branch-compare-type: ANT
                  branch-pattern: '**'
          custom-url: '* $JOB_NAME $BUILD_URL'
    wrappers:
      - timeout:
          fail: true
          write-description: true
          timeout: 10
