- job:
    name: verify-jeepyb-config
    builders:
      - shell:
          !include-raw: './builders/verify-jeepyb-config.py'
    description: 'This job makes syntax check for jeepyb config projects.yml'
    logrotate:
      numToKeep: 100
      daysToKeep: 90
    node: verify-jeepyb-config
    concurrent: true
    parameters:
      - string:
          name: GERRIT_REFSPEC
          default: 'refs/heads/master'
    properties:
      - heavy-job:
          weight: 1
    scm:
      - git:
          branches:
            - $GERRIT_BRANCH
          remotes:
            - gerrit:
                refspec: $GERRIT_REFSPEC
                url: 'ssh://infra-ci@review.fuel-infra.org:29418/fuel-infra/jeepyb-config'
                credentials-id: '70105253-c857-4463-a927-f47307911e45'
          choosing-strategy: gerrit
    triggers:
      - gerrit:
          trigger-on:
            - patchset-created-event
          projects:
            - project-compare-type: PLAIN
              project-pattern: fuel-infra/jeepyb-config
              branches:
                - branch-compare-type: ANT
                  branch-pattern: '**'
              file-paths:
                - compare-type: 'PLAIN'
                  pattern: 'projects.yaml'
          custom-url: '* $JOB_NAME $BUILD_URL'
    wrappers:
      - timeout:
          fail: true
          write-description: true
          timeout: 10
