- project:
    name: 'Mitaka fuel-library puppet-openstack deployment tests'
    ubuntu_dist: 'trusty'
    projectpackage: 'fuel-library9.0'
    deb-mirror-base-name: '9.0 mos9.0'
    rpm-mirror-base-name: 'mos9.0-centos7'
    branch-id: 'mitaka'
    fuellib-branch: 'stable/mitaka'
    fuelmirror-branch: 'stable/mitaka'
    puppet-branch: 'stable/mitaka'
    puppet-projects-regexp: '{mitaka_puppet_openstack_projects_regexp}'
    gerrit-macro: 'puppet-openstack-request-mitaka'
    properties: ''
    venvpath: '/home/jenkins/venv-nailgun-tests-2.9'
    timeout: 200
    jobs:
      - '{branch-id}.puppet-openstack.fuel-library.pkgs.{dist}.{testgroup}':
          dist: ubuntu
          testgroup: smoke_neutron
          properties: |
            CUSTOM_ENV=true
            BUILD_IMAGES=true

      - '{branch-id}.puppet-openstack.fuel-library.pkgs.{dist}.{testgroup}':
          dist: ubuntu
          testgroup: neutron_vlan_ha
          properties: |
            SYNC_DEPL_TASKS=true
            KEEP_BEFORE=yes

- project:
    name: 'Newton fuel-library puppet-openstack deployment tests'
    ubuntu_dist: 'xenial'
    projectpackage: 'fuel-library10.0'
    deb-mirror-base-name: '10.0 mos10.0'
    rpm-mirror-base-name: 'mos10.0-centos7'
    branch-id: 'newton'
    fuellib-branch: 'stable/newton'
    fuelmirror-branch: 'stable/newton'
    puppet-branch: 'stable/newton'
    puppet-projects-regexp: '{puppet_openstack_projects_regexp}'
    gerrit-macro: 'puppet-openstack-request-newton'
    properties: ''
    venvpath: '/home/jenkins/venv-nailgun-tests-2.9'
    timeout: 200
    jobs:
      # NOTE(mkarpin): as workaround for https://bugs.launchpad.net/fuel/+bug/1623394
      # memory is set to 4096, to unblock CI of master in upstream
      - '{branch-id}.puppet-openstack.fuel-library.pkgs.{dist}.{testgroup}':
          dist: ubuntu
          testgroup: smoke_neutron
          properties: |
            CUSTOM_ENV=true
            BUILD_IMAGES=true
            SLAVE_NODE_MEMORY=4096

      - '{branch-id}.puppet-openstack.fuel-library.pkgs.{dist}.{testgroup}':
          dist: ubuntu
          testgroup: review_in_fuel_library
          properties: |
            CUSTOM_ENV=true
            BUILD_IMAGES=true

- project:
    name: 'Ocata fuel-library puppet-openstack deployment tests'
    ubuntu_dist: 'xenial'
    projectpackage: 'fuel-library11.0'
    deb-mirror-base-name: '11.0 mos11.0'
    rpm-mirror-base-name: 'mos11.0-centos7'
    branch-id: 'ocata'
    fuellib-branch: 'stable/ocata'
    fuelmirror-branch: 'stable/ocata'
    puppet-branch: 'stable/ocata'
    puppet-projects-regexp: '{puppet_openstack_projects_regexp}'
    gerrit-macro: 'puppet-openstack-request-ocata'
    properties: ''
    venvpath: '/home/jenkins/venv-nailgun-tests-2.9'
    timeout: 200
    jobs:
      # NOTE(mkarpin): as workaround for https://bugs.launchpad.net/fuel/+bug/1623394
      # memory is set to 4096, to unblock CI of master in upstream
      - '{branch-id}.puppet-openstack.fuel-library.pkgs.{dist}.{testgroup}':
          dist: ubuntu
          testgroup: smoke_neutron
          properties: |
            CUSTOM_ENV=true
            BUILD_IMAGES=true
            SLAVE_NODE_MEMORY=4096

      - '{branch-id}.puppet-openstack.fuel-library.pkgs.{dist}.{testgroup}':
          dist: ubuntu
          testgroup: review_in_fuel_library
          properties: |
            CUSTOM_ENV=true
            BUILD_IMAGES=true

- project:
    name: 'Master fuel-library puppet-openstack deployment tests'
    ubuntu_dist: 'xenial'
    projectpackage: 'fuel-library10.0'
    deb-mirror-base-name: 'master mos-master'
    rpm-mirror-base-name: 'mos-master-centos7'
    branch-id: 'master'
    fuellib-branch: 'master'
    fuelmirror-branch: 'master'
    puppet-branch: 'master'
    puppet-projects-regexp: '{puppet_openstack_projects_regexp}'
    gerrit-macro: 'puppet-openstack-request-master'
    properties: ''
    venvpath: '/home/jenkins/venv-nailgun-tests-2.9'
    timeout: 200
    jobs:
      # NOTE(mkarpin): as workaround for https://bugs.launchpad.net/fuel/+bug/1623394
      # memory is set to 4096, to unblock CI of master in upstream
      - '{branch-id}.puppet-openstack.fuel-library.pkgs.{dist}.{testgroup}':
          dist: ubuntu
          testgroup: smoke_neutron
          properties: |
            CUSTOM_ENV=true
            BUILD_IMAGES=true
            SLAVE_NODE_MEMORY=4096

      - '{branch-id}.puppet-openstack.fuel-library.pkgs.{dist}.{testgroup}':
          dist: ubuntu
          testgroup: review_in_fuel_library
          properties: |
            CUSTOM_ENV=true
            BUILD_IMAGES=true
