- job-template:
    name: 'infra-publish'
    project-type: freestyle
    concurrent: false
    node: '{infra-publish-node}'
    properties:
      - inject:
          properties-content: |
            REPO_BASE_PATH={repo-base-path}
            SIGKEYID={pkg-sign-key}
    parameters:
      - string:
          name: PROJECT_NAME
          default: '{name}'
      - string:
          name: PROJECT_VERSION
          default: '{release}'
      - bool:
          name: IS_UPDATES
          default: '{is-updates}'
    wrappers:
      - jenkins
    scm:
      - fuel-infra:
          scm-user: '{scm-user}'
          scm-repo: '{scm-repo}'
          scm-basedir: '{scm-basedir}'
          scm-credentials-id: '{scm-credentials-id}'
          scm-branch: '{scm-branch}'
    builders:
        - shell:
            !include-raw-escape: builders/publish.sh
    publishers:
      - pkgname-as-desc
      - archive-trace-files
      - archive:
          artifacts: '${{DIST}}.publish.setenvfile'
          allow-empty: false
