- project:
    version-id: '9.x'
    name: '{version-id}-baremetal_environments'
    test-type: 'baremetal'
    repobranch: 'master'
    reponame: 'fuel-qa'
    description: '{version-id} baremetal environments group'
    node: 'baremetal'
    timeout: '480'
    properties: ''
    weight: '1'
    jobs:
     - 'fuel.{test-type}.{environment}':
         environment: 'alpha'
         fuel_qa_version: 'origin/stable/mitaka'
         admin_nic: 'eno2'
         admin_vlan: '270'
     - 'fuel.{test-type}.{environment}':
         environment: 'beta'
         fuel_qa_version: 'origin/stable/mitaka'
         admin_nic: 'eno2'
         admin_vlan: '223'