- job:
    name: environment_update
    concurrent: true
    description: |
      Puppet run on slaves
    properties:
      - heavy-job:
          weight: 3
    parameters:
      - node:
         name: NODE
         description: "Select slave"
         ignore-offline-nodes: true
         allowed-multiselect: true
    builders:
      - shell: |
          #!/bin/bash

          set -ex

          sudo /usr/bin/puppet agent -vd --onetime --no-daemonize --noop
          sudo /usr/bin/puppet agent -vd --onetime --no-daemonize

          echo "Description string: $(cat /var/lib/puppet/gitrevision.txt)"

    publishers:
      - email:
          notify-every-unstable-build: true
          recipients: 'ci+alert@mirantis.com'
          send-to-individuals: false
      - description-setter:
          regexp: "'Description string: (.*)'"
          regexp-for-failed: "'Description string: (.*)'"
    wrappers:
        - ansicolor:
            colormap: xterm
